id = "object://micronaut/scxq7"
version = "1.0.0"
class = "micronaut.object.server"
authority = "object"
runtime = "sco/1"
mutability = "none"

[io]
chat = "./io/chat.txt"
stream = "./io/stream.txt"
snapshot_dir = "./io/snapshot"

[brains]
trigrams = "./brains/trigrams.json"
bigrams = "./brains/bigrams.json"
meta_intent_map = "./brains/meta-intent-map.json"

[trace]
scxq2 = "./trace/scxq2.trace"

[proof]
scxq2 = "./proof/scxq2.proof"
